### ISSUE TITLE
How to read weight data when it is stored in a separate file?

### ISSUE THREAD

**Issue by tylike** [nietras/OnnxSharp#7]
Hello! 

I would like to ask, if the weight file of ONNX is saved in a separate file, will it not be read automatically?

I tried to use OnnxSharp to read this model [chatglm-6b-int8.onnx](https://huggingface.co/K024/ChatGLM-6b-onnx-u8s8/blob/main/chatglm-6b-int8-onnx-merged/chatglm-6b-int8.onnx) and it worked well, but I couldn't find the values of the weights.

This is a screenshot of my debugging session. 
<img width="1424" alt="screen" src="https://github.com/nietras/OnnxSharp/assets/920370/7a4fa809-4a22-49e6-b4a4-4304b40a0185">

I would like to ask if OnnxSharp plans to support this feature? 
Or, can you provide any assistance? 

Thank you very much.

**Comment by nietras** [comment]
You must load each onnx file separately. There is no automatic support for it.
